style: github
template: RELEASE.tpl.md
info:
  repository_url: https://github.com/IEEE-VIT/templa-rs
options:
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - fix
      - docs
      - style
      - refac
      - perf
      - test
      - build
      - ci
      - chore
      - revert
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refac: Code Refactoring
      ci: Continuous Integration
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE