name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Vulnerability-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Run Trivy vulnerability scanner in repo mode
          uses: aquasecurity/trivy-action@master
          id: Trivy
          with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
            exit-code: '1'
        
        - if: failure()
          name: Get Trivy Result
          id: Trivy-result
          run: echo "::set-output name=TrivyResult::$(cat trivy-results.sarif | base64)"
          
        - if: failure()
          uses: actions/github-script@v5
          with:
            script: |
              const testFolder = process.cwd();
              const fs = require('fs');

              fs.readdirSync(testFolder).forEach(file => {
                console.log(file);
              });
              console.log(process.cwd())

