name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Vulnerability-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Run Trivy vulnerability scanner in repo mode
          uses: aquasecurity/trivy-action@master
          id: Trivy
          with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'table'
            output: 'trivy-results.sarif'
            severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
            exit-code: '1'
        
        - if: failure()
          uses: actions/github-script@v5
          with:
            script: |
              const fs = require('fs');
              var data  = fs.readFileSync("trivy-results.sarif").toString();
              var md = "```"
              final=""
              final=final.concat(md,data,md);
              console.log(`${final}`)
        
        - if: github.event_name == 'pull_request' && failure()
          uses: actions/github-script@v5
          with:
            script: |
              const fs = require('fs');
              var data  = fs.readFileSync("trivy-results.sarif").toString();
              var md = "```"
              final=""
              final=final.concat(md,data,md);
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `${final}`
              })             
